language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --features=music,pretty_output
  - cargo test --verbose --features=music,pretty_output
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
